### ISSUE TITLE
Tests do not run

### ISSUE THREAD

**Issue by 07BC** [jdlehman/alt-example-tests#2]
Just cloned the repo, ran `npm install` and tried running `npm run test`. On node `0.12.7` and `4.1.0`

```
13:37 $ npm run test

> alt-example-tests@1.0.0 test /Users/jamie.lesouef/Projects/tutorials/alt-example-tests
> karma start

WARN [watcher]: Pattern "/Users/jamie.lesouef/Projects/tutorials/alt-example-tests/node_modules/sinon/lib/../pkg/sinon.js" does not match any file.
WARN [preprocess]: Can not load "webpack"!
  TypeError: this.emitter.refreshFiles is not a function
    at Plugin.notifyKarmaAboutChanges (/Users/jamie.lesouef/Projects/tutorials/alt-example-tests/node_modules/karma-webpack/index.js:108:15)
    at Plugin.<anonymous> (/Users/jamie.lesouef/Projects/tutorials/alt-example-tests/node_modules/karma-webpack/index.js:72:9)
    at Compiler.applyPlugins (/Users/jamie.lesouef/Projects/tutorials/alt-example-tests/node_modules/webpack/node_modules/tapable/lib/Tapable.js:26:37)
    at Watching._done (/Users/jamie.lesouef/Projects/tutorials/alt-example-tests/node_modules/webpack/lib/Compiler.js:78:17)
    at Watching.<anonymous> (/Users/jamie.lesouef/Projects/tutorials/alt-example-tests/node_modules/webpack/lib/Compiler.js:61:18)
    at Compiler.emitRecords (/Users/jamie.lesouef/Projects/tutorials/alt-example-tests/node_modules/webpack/lib/Compiler.js:282:37)
    at Watching.<anonymous> (/Users/jamie.lesouef/Projects/tutorials/alt-example-tests/node_modules/webpack/lib/Compiler.js:58:19)
    at /Users/jamie.lesouef/Projects/tutorials/alt-example-tests/node_modules/webpack/lib/Compiler.js:275:11
    at Compiler.applyPluginsAsync (/Users/jamie.lesouef/Projects/tutorials/alt-example-tests/node_modules/webpack/node_modules/tapable/lib/Tapable.js:60:69)
    at Compiler.afterEmit (/Users/jamie.lesouef/Projects/tutorials/alt-example-tests/node_modules/webpack/lib/Compiler.js:272:8)
INFO [karma]: Karma v0.12.37 server started at http://localhost:9876/
INFO [launcher]: Starting browser PhantomJS
INFO [PhantomJS 1.9.8 (Mac OS X 0.0.0)]: Connected on socket -j6R1p7Jh4_ui5eHRtZn with id 69023428
PhantomJS 1.9.8 (Mac OS X 0.0.0) ERROR
  SyntaxError: Parse error
  at /Users/jamie.lesouef/Projects/tutorials/alt-example-tests/test/actions/PetActions_test.js:1
PhantomJS 1.9.8 (Mac OS X 0.0.0): Executed 0 of 0 ERROR (0.025 secs / 0 secs)

npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "test"
npm ERR! node v4.1.0
npm ERR! npm  v2.14.3
npm ERR! code ELIFECYCLE
npm ERR! alt-example-tests@1.0.0 test: `karma start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the alt-example-tests@1.0.0 test script 'karma start'.
npm ERR! This is most likely a problem with the alt-example-tests package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     karma start
npm ERR! You can get their info via:
npm ERR!     npm owner ls alt-example-tests
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/jamie.lesouef/Projects/tutorials/alt-example-tests/npm-debug.log
```

**Comment by jdlehman** [comment]
@jamielesouef I believe this is because `npm run test` is trying to use the global version of `karma`.  I have updated the npm script to point to the version of karma in the package file.

Let me know if this does not solve your problem.

**Comment by jdlehman** [comment]
I also added travis integration so that we can ensure that tests do not break in the future

**Comment by allenroam** [comment]
got the same error, karma starts in the beginning. but when refreshing page, it shows this.emitter.refreshFiles is not a function

**Comment by jdlehman** [comment]
@whatsupallen I updated the codebase to use [jest](http://facebook.github.io/jest/) as the test runner instead of Karma. This should help resolve some of the issues people were seeing with Karma.
